# Hybrid mode — redSLC on SD + sys MLC (internal)
# DeploymentMode = 'Hybrid'
# Leave the SD inserted while Kiosk Menu runs.

[partitions]
slccmpt=true
slc=true
mlc=false

[scfm]
disable=false
allow_sys=true

[disable_encryption]
mlc=false

[sys_mount]
mlc=false
